name: scrolling_years_calendar_nullsafety
description: A calendar widget to easily scroll through the years, allowing for customizations to fit your design. Forked from https://github.com/mennorenkens/flutter_scrolling_calendar
version: 2.0.0-nullsafety.1
homepage: https://github.com/marcosneivanery/flutter_scrolling_calendar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
